# -*- coding: utf-8 -*-
"""Python Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Luchio9/eecda902dad7b0a0c0ac8eeae581c95e/python-chatbot.ipynb
"""

pip install nltk

pip install newspaper3k

#Import the libraries
from newspaper import Article
import random
import string
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import warnings
warnings.filterwarnings('ignore')

#Download the punkt package
nltk.download('punkt', quiet=True)

#Get the article
article = Article('https://netdoktor.dk/sygdomme/fakta/influenza.htm')
article = Article('https://netdoktor.dk/sygdomme/fakta/diabetes.htm')
article.download()
article.parse()
article.nlp()
corpus = article.text

#Print the articles text
print(corpus)

#Tokenization
text = corpus
sentence_list = nltk.sent_tokenize(text) # A list of sentences

#Print the list of sentences
print(sentence_list)

# A function to return a random greeting response to a users greeting
def greeting_response(text):
  text = text.lower()

  #Bots greeting reponse
  bot_greetings = ['Hej', 'Halløj', 'Hejsa', 'Goddag']
  #Users greeting
  user_greetings = ['Hej', 'Halløj', 'Hejsa', 'Goddag', 'Hvad så', 'Hva så']


  for word in text.split():
    if word in user_greetings:
      return random.choice(bot_greetings)

def index_sort (list_var):
  length = len(list_var)
  list_index = list(range(0, length))

  x = list_var
  for i in range(length):
    for j in range(length):
      if x[list_index[i]] > x[list_index[j]]:
        #Swap
        temp = list_index[i]
        list_index[i] = list_index[j]
        list_index[j] = temp
        
        return list_index

#Create the bots response
def bot_response(user_input):
  user_input = user_input.lower()
  sentence_list.append(user_input)
  bot_response = ''
  cm = CountVectorizer().fit_transform(sentence_list)
  similarity_scores = cosine_similarity(cm[-1], cm)
  similarity_scores_list = similarity_scores.flatten()
  index = index_sort(similarity_scores_list)
  index = index[1:]
  response_flag = 0

  j = 0
  for i in range(len(index)):
    if similarity_scores_list[index[i]] > 0.0:
      bot_response = bot_response+' '+sentence_list[index[i]]
      response_flag = 1
      j = j+1
    if j > 2:
      break

  if response_flag == 0:
    bot_response = bot_response+' '+"Beklager, jeg forstår ikke."

  sentence_list.remove(user_input)

  return bot_response

#Start the chat
print('Doc bot: Jeg kan svare på dine spørgsmål om forskellige sygdomme. Hvis du vil stoppe samtalen, skriv farvel.')

exit_list = ['exit', 'farvel', 'vi ses']

while(True):
  user_input = input()
  if user_input.lower() in exit_list:
    print('Doc bot: Vi snakkes ved senere !')
    break
  else:
    if greeting_response(user_input) != None:
      print('Doc bot: '+greeting_response(user_input))
    else:
      print('Doc bot: '+bot_response(user_input))